title: "0x4"
author: Dani Pragustia
github: danipragustia
description_profile: "Only guy ramming code on computer."
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

config:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- articles.md

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - lograth-jekyll.gemspec
